# Generated by Django 5.2.9 on 2025-12-07 23:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_psico', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='Nivel Psico')),
                ('modo_psicologico', models.CharField(choices=[('Empático', 'Empático'), ('Técnico', 'Técnico'), ('Élite', 'Élite')], default='Empático', max_length=30, verbose_name='Modo Psicológico')),
                ('modo_competencia', models.BooleanField(default=False, verbose_name='Modo Competencia')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('mensaje_usuario', models.TextField(verbose_name='Pregunta del Usuario')),
                ('respuesta_ia', models.TextField(verbose_name='Respuesta de KAIROS')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MetricasFisicas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.DecimalField(decimal_places=2, help_text='Peso en Kg', max_digits=5)),
                ('altura', models.DecimalField(decimal_places=2, help_text='Altura en Metros', max_digits=5)),
                ('edad', models.IntegerField()),
                ('nivel', models.CharField(choices=[('Bajo', 'Bajo'), ('Medio', 'Medio'), ('Alto', 'Alto')], default='Bajo', max_length=30, verbose_name='Nivel de Experiencia')),
                ('objetivo', models.CharField(choices=[('Aumentar Músculo', 'Aumentar Músculo'), ('Definición', 'Definición'), ('Mejorar Resistencia', 'Mejorar Resistencia'), ('Aumentar Fuerza', 'Aumentar Fuerza'), ('Bienestar', 'Bienestar')], default='Bienestar', max_length=30, verbose_name='Objetivo Principal')),
                ('deporte', models.CharField(choices=[('Calistenia', 'Calistenia'), ('Fuerza/Gimnasio', 'Fuerza/Gimnasio'), ('Resistencia/Cardio', 'Resistencia/Cardio'), ('Fitness funcional', 'Fitness funcional'), ('Combate/Artes Marciales', 'Combate/Artes Marciales'), ('Movilidad/Mente', 'Movilidad/Mente')], default='Fitness funcional', max_length=30, verbose_name='Deporte Principal')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
