# Generated by Django 5.2.8 on 2025-12-09 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuracion",
            name="modo_psicologico",
            field=models.CharField(
                choices=[(1, "Empático"), (2, "Técnico"), (3, "Élite")],
                default="Empático",
                max_length=30,
                verbose_name="Modo Psicológico",
            ),
        ),
    ]
