# Generated by Django 5.2.8 on 2025-12-09 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_alter_configuracion_modo_psicologico"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuracion",
            name="modo_psicologico",
            field=models.IntegerField(
                choices=[(1, "Empático"), (2, "Técnico"), (3, "Élite")],
                default=1,
                verbose_name="Modo Psicológico",
            ),
        ),
    ]
